### ISSUE TITLE
REST API 

### ISSUE THREAD

**Issue by peppelinux** [UniversitaDellaCalabria/uniTicket#2]
Utilizziamo:
- https://www.django-rest-framework.org/

Sistema di autenticazione:
- Token rilasciato arbitrariamente con scadenza opzionale. In caso di revoca provvedere disabilitando il token o rimuovendolo. Ogni Token deve essere associato ad una identità anagrafica corrispondente al referente tecnico o organizzativo del sistema utilizzatore

**Comment by peppelinux** [comment]
Considerare:

https://github.com/teamdigitale/api-openapi-samples/tree/master/openapi-v3
https://github.com/teamdigitale?utf8=✓&q=openapi&type=&language=

**Comment by peppelinux** [comment]
Di seguito descritte le funzionalità da implementare:

settori/ torna tutti gli uffici/settori di competenza
tipo/richieste/[settore_id] torna tutti i tipi di richiesta (moduli compilabili) - per ufficio o per tutti
tipo/id_tipo torna lo schema da utilizzare (fields name e attributi di questi) per fare un POST di richiesta
tipo/id_tipo/new submit di un modulo compilato
richieste/[all] torna tutte le richieste attive (if all: torna tutte anche le chiuse)
richiesta/id_tipo/stato stato della richiesta (chiuso, aperto)
richiesta/id_tipo/ ... altre informazioni sulla richiesta

**Comment by peppelinux** [comment]
# Roadmap

- [x] Create a the django rest base application (https://github.com/UniversitaDellaCalabria/uniTicket/commit/43289306f7c905b2be7a6d2a65bf8099b54b23d0)
- [x] Create a Ticket API resource for get a form module (GET) and submit it (POST) (https://github.com/UniversitaDellaCalabria/uniTicket/commit/e1b773d976de5b53fcc59fdb30d5f0caae1e3956)
  - [ ] base unit tests 
  - [ ] example data dump with a special ticket will all the possibile dynamic form field (@francesco-filicetti )
  - [ ] extended unit tests with all dynamic form fields
- [ ] Create get Strutture API
- [ ] Create get Ticket Categories API
- [ ] Create get Ticket Status API (with all the messages in)
- [ ] Create get created Ticket List (paginated with status attributes)
- [ ] Create Close Ticket
- [ ] Create get Statistics per struttura
- [ ] Create get Statistics per ticket
- [ ] Create get General Statistics

**Comment by peppelinux** [comment]
all these commits have been commited to v2.0.0 branch
